services:
  # Next.jsアプリケーション
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doujin-app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      db:
        condition: service_started
      rustfs-init:
        condition: service_completed_successfully
    networks:
      - doujin-net

  # PostgreSQLデータベース
  db:
    image: postgres:17-alpine
    container_name: doujin-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck: # DBのヘルスチェックを追加 (appの起動前にDB準備完了を待つため)
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres} || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    networks:
      - doujin-net

  # RustFS
  storage:
    image: rustfs/rustfs:latest
    container_name: doujin-storage
    command: /data 
    volumes:
      - rustfs_data:/data 
    env_file:
      - .env
    environment:
      RUSTFS_ACCESS_KEY: ${S3_ACCESS_KEY:-rustfsadmin} 
      RUSTFS_SECRET_KEY: ${S3_SECRET_KEY:-rustfsadmin}
      RUSTFS_ADDRESS: ":9000"
      RUSTFS_CONSOLE_ADDRESS: ":9001"
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_CORS_ALLOWED_ORIGINS: "*"
      RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS: "*" 
      RUSTFS_LOG_LEVEL: info
    ports:
      - "9000:9000"  # API用ポート
      - "9001:9001"  # 管理画面用ポート
    networks:
      - doujin-net
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "sh", "-c", "curl -f http://localhost:9000/health"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 40s

  # RustFS初期化
  rustfs-init:
      image: amazon/aws-cli:latest
      container_name: rustfs-init
      depends_on:
        storage: 
          condition: service_healthy
      networks:
        - doujin-net
      env_file:
        - .env
      environment:
        AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY:-rustfsadmin}
        AWS_SECRET_ACCESS_KEY: ${S3_SECRET_KEY:-rustfsadmin}
        AWS_ENDPOINT_URL: http://storage:9000
        AWS_DEFAULT_REGION: us-east-1
      volumes:
        # policy.json と init-rustfs.sh の両方をマウント
        - ./rustfs-init:/aws/config 
      # entrypoint を /bin/sh に変更
      entrypoint: /bin/sh
      # command でスクリプトを実行
      command: -c "chmod +x /aws/config/init-rustfs.sh && /aws/config/init-rustfs.sh"

volumes:
  postgres_data:
  rustfs_data: # 新しいボリューム定義

networks:
  doujin-net:
    driver: bridge